name: pynrc

dependencies:
    - python=3.5
    - numpy>=1.13
    - matplotlib>=2.0.2
    - astropy>=3
    - Cython
    - pip:
        - sphinx>=1.5.1
        - sphinx-automodapi
        - ipykernel
        - nbsphinx
        - git+https://github.com/spacetelescope/poppy.git#egg=poppy
        - git+https://github.com/spacetelescope/webbpsf.git#egg=webbpsf
        - git+https://github.com/spacetelescope/pysynphot.git#egg=pysynphot

